### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by GorkemKurter** [TLeonardUK/ds2os#1]
There is no relase in the relaeses section?

**Comment by Jakerino** [comment]
It will come when it comes. I'm sure it was painstaking work getting this working for 3. 

Take your time @TLeonardUK  thank you for your hard work.

**Comment by AXDZ12** [comment]
I am a fans of dark Souls. Shall I ask when the Ds2os can be download (and I really thank @TLeonardUK do in ds3os so I can play ds3 now with my friends)
