### ISSUE TITLE
Failed to write full patch to memory

### ISSUE THREAD

**Issue by VenganzaD** [TLeonardUK/ds2os#10]
The loader was built without any issue. 

![image](https://user-images.githubusercontent.com/108952669/178077845-9e926b90-b919-41ae-990f-60badb9ae1d8.png)

It's failing to patch, but I am running both the game and loader as admin. Not sure if it would matter, but the game is as fresh of an install as possible and the game is not installed to C:

Appreciate any guidance.

**Comment by Littdds** [comment]
How did you do that, man

**Comment by TLeonardUK** [comment]
Read the large warning text on the front page of this depot.

**Comment by VenganzaD** [comment]
I am aware that you said it's nonfunctional, but that wasn't exactly clear to what regard. You could say its not functional if something as small as bloodstains/messages aren't showing as intended. Wasn't sure if patching was where the nonfunctional started or I wasn't building it correctly.
