### ISSUE TITLE
Is there any chance that you will work on this project?

### ISSUE THREAD

**Issue by Savalige** [TLeonardUK/ds2os#13]
Hello, I was wondering if there is any chance that you would resume work on this project or if it has been completely abandoned?

**Comment by Dsplayer231** [comment]
Two year!

**Comment by ItsZman2006** [comment]
I imagine he has his hands full with solving ds3os's issues. I'm wondering this question as well because I think having our own servers where we can coop without worrying about soul memory and soul level would be awesome :D

**Comment by Savalige** [comment]
I started converting his implementation of ds3os for ds2 and I can get the players to connect to the server. But I am having issues with sending messages from the server to the clients instead of just responding to the clients messages and you need to send a message to allow players to join each others worlds so it is still quite useless.

**Comment by ItsZman2006** [comment]
Hey this is a huge step forward in the right direction though! Don't give up on it! I believe you are the closest person to achieving a ds2 private server so please try to keep at it :D Don't give up skeleton!

**Comment by ItsZman2006** [comment]
I hope we can get this server up and running soon! I would love to make a Coop mod for Dark Souls 2

**Comment by ItsZman2006** [comment]
Could you maybe upload your build of ds2os? (With the creators permission of course) Perhaps if you upload what you have someone may be able to help speed up development time and get servers up?

Edit: All thats left to do is get summoning working right? Bloodstains and messages work correctly?

**Comment by Savalige** [comment]
Most things don't work what I have verified works is the death counter which is what I used to make sure that we where actually connected, which did work. I have mostly been looking into getting summoning and the likes to work since they are essential for multiplayer gameplay to function. They probably use a different message for bloodstains so that is something that needs to be figured out as well. The main thing that I know is stopping the summoning is that the server can't send messages independently only respond to the clients messages, so no messages either since they also rely on the sever sending messages.

I can look into getting it up on github tho

**Comment by ItsZman2006** [comment]
Are you still working on this?

**Comment by TLeonardUK** [comment]
No actively no.

**Comment by TLeonardUK** [comment]
Dark Souls 2 support is being integrated directly into DS3OS, see https://github.com/TLeonardUK/ds3os for details.

Closing down all tickets and archiving this repo.
