### ISSUE TITLE
Not really an issue just a few questions

### ISSUE THREAD

**Issue by ItsZman2006** [TLeonardUK/ds2os#14]
Hey! Just had a few questions about this project :D

1. What kind of work and how much work would need to be done to at least get coop multiplayer functioning?
2. If you do continue to work on this project what versions of DS2 will be supported?
3. I know you got asked this previously but I'm asking anyway. Are you at some point going to go back to this project? Im sure many people would love to have access to their own servers for this game.

Just thought Id ask as I was a little curious about this :D Love your work on ds3os by the way. It's much better to have my own little server to play on and coop than worry about running into hackers on the main servers :D Plus having mod support is awesome!

**Comment by TLeonardUK** [comment]
Dark Souls 2 support is being integrated directly into DS3OS, see https://github.com/TLeonardUK/ds3os for details.

Closing down all tickets and archiving this repo.
