### ISSUE TITLE
Building Issue (DS2OS)

### ISSUE THREAD

**Issue by t1mb3rw0lf** [TLeonardUK/ds2os#3]
Loader.exe was built without any errors and works pretty fine, but only shows DS3 open servers, think it still uses DS3OS MasterServer. That is ok.

The real problem is that I get either **LNK2019** errors or **C4996** errors. I tried building OpenSSL _1.0.1_, _1.1.0_ and even _3.1.0_, but none of them worked. I set all the dependencies and additional directories, but still no hope.
Is that even possible to build DS2 **Server.exe** at this moment?

P.S. **vcpkg** is installed and works, tried to install OpenSSL via vcpkg too, didn't help. Any suggestions?

**Comment by TLeonardUK** [comment]
This repo is just a fork of DS3OS at the moment, it's non-functional, as the readme says at the top, please do not use it.

**Comment by t1mb3rw0lf** [comment]
Got you, thank you. I had too much hope, lol. Good luck in finishing this project, it is really useful. Seems like FROMSOFTWARE not gonna bring back servers.
