### ISSUE TITLE
Dark souls II or Dark Souls II: Scholar of the First Sin?

### ISSUE THREAD

**Issue by Pacifist-Penguin** [TLeonardUK/ds2os#8]
Well, that's the question. Is this server created (or should I say planned) for the original Dark Souls II or Dark Souls II: Scholar of the First Sin?

Thank you for your great work anyway. DS3os preserves this great game for future.

**Comment by ZkilleMito** [comment]
No longer thinking about coming back with the project to finish DS2OS?

**Comment by TLeonardUK** [comment]
Dark Souls 2 support is being integrated directly into DS3OS, see https://github.com/TLeonardUK/ds3os for details.

Closing down all tickets and archiving this repo.

(Also to answer your original question, I'm working on SOTFS).
