### ISSUE TITLE
No longer thinking about coming back with the project to finish DS2OS?

### ISSUE THREAD

**Issue by ZkilleMito** [TLeonardUK/ds2os#9]
I play the ds2 a lot and I believe there are many people who still play this game, if it ends, it would be great to call the ds2 public that is without hope.

**Comment by XHoroWiseX** [comment]
I would love to play coop again with my friends
I will be glad if you return to the project and continue work

**Comment by TLeonardUK** [comment]
I intend to. But before putting in the large amount of effort required, I'm going to wait nd see what From does when they bring the official servers back online.

**Comment by Arax20** [comment]
If you open up donations, I'm sure people would be happy to pitch in. Might help justify the time investment

**Comment by TLeonardUK** [comment]
Dark Souls 2 support is being integrated directly into DS3OS, see https://github.com/TLeonardUK/ds3os for details.

Closing down all tickets and archiving this repo.
